version: '3.1'
services:

  db:
    container_name: mysql
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: offers
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "6603:3306"

